(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";function _interopRequireDefault(t){return t&&t.__esModule?t:{default:t}}function _classCallCheck(t,i){if(!(t instanceof i))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(exports,"__esModule",{value:!0});var _createClass=function(){function t(t,i){for(var e=0;e<i.length;e++){var s=i[e];s.enumerable=s.enumerable||!1,s.configurable=!0,"value"in s&&(s.writable=!0),Object.defineProperty(t,s.key,s)}}return function(i,e,s){return e&&t(i.prototype,e),s&&t(i,s),i}}(),_utils=require("./utils"),_MountainLine=require("./MountainLine"),_MountainLine2=_interopRequireDefault(_MountainLine),_class=function(){function t(i,e,s,n,h){_classCallCheck(this,t),this.ctx=i,this.width=e,this.height=s,this.color=n,this.isNight=h,this.nbLayers=(0,_utils.getRandomInt)(2,11),this.sky=this.height-(0,_utils.getRandomInt)(-50,this.height/2),i.clearRect(0,0,e,s)}return _createClass(t,[{key:"drawSky",value:function(){if(this.isNight){this.ctx.fillStyle="hsl("+this.color+", 10%, 10%)",this.ctx.rect(0,0,this.width,this.height),this.ctx.fill(),this.ctx.fillStyle="#eee";for(var t=0;t<1e3;++t)this.ctx.fillRect((0,_utils.getRandomInt)(0,this.width),(0,_utils.getRandomInt)(0,this.height),1,1)}else this.ctx.fillStyle="hsl("+this.color+", 30%, 90%)",this.ctx.rect(0,0,this.width,this.height),this.ctx.fill()}},{key:"drawMountains",value:function(){for(var t=this.nbLayers;t>0;--t){this.ctx.fillStyle="hsl("+this.color+", "+10*t+"%, "+10*(t+1)+"%)";var i=new _MountainLine2.default(this.ctx,this.height-(t*(this.sky/this.nbLayers)-this.nbLayers/10),this.width);i.render()}}},{key:"render",value:function(){this.drawSky(),this.drawMountains()}}]),t}();exports.default=_class;
},{"./MountainLine":3,"./utils":6}],2:[function(require,module,exports){
"use strict";function _classCallCheck(t,e){if(!(t instanceof e))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(exports,"__esModule",{value:!0});var _createClass=function(){function t(t,e){for(var i=0;i<e.length;i++){var s=e[i];s.enumerable=s.enumerable||!1,s.configurable=!0,"value"in s&&(s.writable=!0),Object.defineProperty(t,s.key,s)}}return function(e,i,s){return i&&t(e.prototype,i),s&&t(e,s),e}}(),_utils=require("./utils"),_class=function(){function t(e,i,s,h){_classCallCheck(this,t),this.ctx=e,this.bridgeHeight=i,this.width=s,this.height=h}return _createClass(t,[{key:"_arch",value:function(t,e,i,s,h){t.lineTo(e,h),t.bezierCurveTo(e,h-i,e+s,h-i,e+s,h)}}]),_createClass(t,[{key:"render",value:function(){var t=(0,_utils.getRandomInt)(0,10)%2===0?(0,_utils.getRandomInt)(0,10):(0,_utils.getRandomInt)(0,50)*-1,e=1.5*this.bridgeHeight;for(this.ctx.beginPath(),this.ctx.moveTo(0,this.height-this.bridgeHeight),this.ctx.lineTo(0,this.height);t<this.width;)this._arch(this.ctx,t,this.bridgeHeight,e,this.height),t+=e+10;this.ctx.lineTo(this.width,this.height-this.bridgeHeight),this.ctx.closePath(),this.ctx.stroke(),this.ctx.fillStyle="#fff",this.ctx.fill()}}]),t}();exports.default=_class;

},{"./utils":6}],3:[function(require,module,exports){
"use strict";function _classCallCheck(t,e){if(!(t instanceof e))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(exports,"__esModule",{value:!0});var _createClass=function(){function t(t,e){for(var i=0;i<e.length;i++){var s=e[i];s.enumerable=s.enumerable||!1,s.configurable=!0,"value"in s&&(s.writable=!0),Object.defineProperty(t,s.key,s)}}return function(e,i,s){return i&&t(e.prototype,i),s&&t(e,s),e}}(),_utils=require("./utils"),_class=function(){function t(e,i,s){_classCallCheck(this,t),this.ctx=e,this.startheight=i,this.width=s}return _createClass(t,[{key:"_drawSlope",value:function(t,e,i){return t.lineTo(e,i),{x:(0,_utils.getRandomInt)(e,e+5),y:(0,_utils.getRandomInt)(i+6,i-5)}}}]),_createClass(t,[{key:"render",value:function(){var t=0,e=this.startheight;for(this.ctx.beginPath(),this.ctx.moveTo(t,e);t<this.width;){var i=this._drawSlope(this.ctx,t,e);t=i.x,e=i.y}this.ctx.lineTo(t,this.width),this.ctx.lineTo(0,this.width),this.ctx.lineTo(0,this.startheight),this.ctx.fill()}}]),t}();exports.default=_class;
},{"./utils":6}],4:[function(require,module,exports){
"use strict";function _classCallCheck(t,i){if(!(t instanceof i))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(exports,"__esModule",{value:!0});var _createClass=function(){function t(t,i){for(var e=0;e<i.length;e++){var s=i[e];s.enumerable=s.enumerable||!1,s.configurable=!0,"value"in s&&(s.writable=!0),Object.defineProperty(t,s.key,s)}}return function(i,e,s){return e&&t(i.prototype,e),s&&t(i,s),i}}(),_class=function(){function t(i,e,s,h,n,a){_classCallCheck(this,t),this.ctx=i,this.height=e,this.width=s,this.x=h,this.callback=a,this.trainWidth=30,this.trainHeight=10,this.ctx.fillStyle="black",this.y=e-n-this.trainHeight}return _createClass(t,[{key:"render",value:function(){this.ctx.clearRect(this.x,this.trainWidth,this.width,this.height),this.ctx.beginPath(),this.ctx.rect(++this.x,this.y,this.trainWidth,this.trainHeight),this.ctx.fill(),this.x>this.width?this.callback():window.requestAnimationFrame(this.render.bind(this))}}]),t}();exports.default=_class;

},{}],5:[function(require,module,exports){
"use strict";function _interopRequireDefault(e){return e&&e.__esModule?e:{default:e}}function draw(){var e=0,t=(0,_utils.getRandomInt)(0,360),r=t<300&&t>200,i=new _Background2.default(bgCtx,width,height,t,r),a=new _Bridge2.default(bgCtx,height/10,width,height),n=new _Train2.default(fgCtx,height,width,e,height/10,draw);i.render(),a.render(),window.requestAnimationFrame(n.render.bind(n))}var _Background=require("./Background"),_Background2=_interopRequireDefault(_Background),_Bridge=require("./Bridge"),_Bridge2=_interopRequireDefault(_Bridge),_Train=require("./Train"),_Train2=_interopRequireDefault(_Train),_utils=require("./utils"),bgCanvas=document.getElementById("tutoriel1"),bgCtx=bgCanvas.getContext("2d"),fgCanvas=document.getElementById("tutoriel2"),fgCtx=fgCanvas.getContext("2d"),width=Math.max(bgCanvas.width,fgCanvas.width),height=Math.max(bgCanvas.height,fgCanvas.height);draw();
},{"./Background":1,"./Bridge":2,"./Train":4,"./utils":6}],6:[function(require,module,exports){
"use strict";function getRandomInt(t,e){return t=Math.ceil(t),e=Math.floor(e),Math.floor(Math.random()*(e-t))+t}Object.defineProperty(exports,"__esModule",{value:!0}),exports.getRandomInt=getRandomInt;

},{}]},{},[5]);
